name: Build, Test, and Push

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. This enables the 'gha' cache support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Build and Run Tests
      - name: Build and Run Tests
        uses: docker/build-push-action@v6
        with:
          context: .
          target: tester
          load: true  # This 'loads' the image into the local docker list so you can 'run' it
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: docker run bot-tester # Use the name/tag from the step above if needed

      # 3. Login and Push (only if tests pass)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Production
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/viyi/serverboizbot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max